[package]
name = "output_testing"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
orion_numbers = { git = "https://github.com/gizatechxyz/orion", package = "orion-numbers", rev = "8329774" }

[tool.agent]
definitions = "proto/oracle.proto" # required

[cairo]
enable-gas = false
