[package]
name = "cairo-oracle-hint-processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-lang-casm = "2.4.4"
cairo-lang-utils = "2.4.4"
cairo-lang-runner = "2.4.4"
cairo-vm = "0.8.4-rc.0"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.17"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
serde_json = "1.0.111"
starknet-types-core = "0.0.7"
